* Atlantic Rhythm
- Naming
  - The Polyrhythmic Diaspora
  - Afro-Atlantic, would include west coast of Africa as well
  - No: Afro-Americas
- Targets
  - Afro-Brazilian
  - Afro-Carribean
- To do
  - A "Just the beats, mam" version
    - Is that youtube playlist?
- Inbox
  - [[https://www.youtube.com/playlist?list=OLAK5uy_kyC-8LFX3U4Dh3WrTH_dJebFreKDwZUuo][Soundway presents Colombia! (The Golden Age of Discos Fuentes. The Powerhouse of Colombian Music 1960-76)]]
      
The goal of this document is to explain the goals of my musical
searching. Of course, it's all about me, me, me. To make it worth the
readers time, many links to (IMHO) good music are provided.  To quote
Laurie Anderson, "talking about music is like dancing about
architecture." So the clearest way to illustrate my goals is to
provide similar music I have already discovered. To ensure the music
is easy to access, when posible YouTube links are provided.


(Much of the "Brazilian" music references herein is simply that which
started in Brazil yet somehow got into the ears of a knownothing
American such that he could report of it. As such some of that is
bastardized. 

Consider 1947's Manteca:
https://www.youtube.com/watch?v=s2Tt6W-TxXs

This is arguably THE song where Afro-Cuban polyrhythm enter American
music. Gillespie describes how the composition was a collaboration
between himself and Chano Pozo, the Cuban drummer, with Pozo bringing
the seeds to the table:
[[https://www.youtube.com/watch?v=BzPO3uO5rFs][How Chano Pozo and Dizzy Gillespie Cooked up "Manteca"]]

Humorously, even Dizzy's band, some of the best American jazz
musicians of the time, simply didn't have polyrhymic skills to play
the song correctly originally -- a song written for them to play.

Note, it was Machito, Mario Bauzá, another important Cuban who
injected the Afro polyrhythm into American music, starting with the
1943 song Tangá (the word being a reference to [[https://www.knkx.org/post/jazz-caliente-latin-jazz-starts-tanga][marijuana]]):
[[https://www.youtube.com/watch?v=DIV4MHb4CT0][Tangá]]

https://www.carnegiehall.org/Blog/2012/11/When-Dizzy-Gillespie-Met-Chano-Pozo

[[https://en.wikipedia.org/wiki/Mario_Bauz%C3%A1][Mario Bauzá, on Wikipedia]]:
"Importantly in 1947, Bauzá introduced the
young Havana conga virtuoso Chano Pozo to Gillespie, when the latter
wanted to add a Cuban percussionist to his band; though Pozo was
killed in a Harlem bar fight just a year later, he left an indelible
and long-lasting mark on Gillespie's playing and compositions,
co-writing several legendary compositions such as "Manteca" and "Tin
Tin Deo".

So, my apologies to the purists. This is written by a white American
trying to catch up with alien musical black magic out of Africa.)


** History of John's search
First, this search started in 2013 and the only target was Cuba i.e.
Afro-Cuban is what I frist discovered. Then I started exploring
Afro-Carribean in general. Obvious Haitian Vodou is heavily Afro influenced:

An academic but excellent tour of Afro-Carribean can be found in the
recording, Drum Jam. The music is much better than the name and album cover imply:
https://www.youtube.com/playlist?list=OLAK5uy_loTrGekcal11QZXvJa3-azBedr5ppTN3A


But any Afro-Latino counts:
https://mailchi.mp/afropop/afro-latino-sounds-of-ecuador-bolivia-and-uruguay
"Afro-Cuban and Afro-Brazilian musical giants have long enjoyed the
spotlight, yet throughout Latin America there are other black enclaves
producing some of the New World's most vibrant music. "

** The goal
      
The core goal is polyrhythmic music.  This is why I prefix things with
"Afro": Afro-Carribean, Afro-Brazilian. Afro-Peruvian is a bit of a
marketing term but I sure do like Novalima.

The goal is the polyrhythm, not roots. Of course the roots of
polyrhythm is out of sub-Saharan Africa.  Polyrhythm is a music theory
concept, but the historical context is obviously the drums. The
sub-Sahara African musical culture was/is heavy on the drums. The
technical nature (limited harmonic and tonal capacity) of drums
steered their musical culture to evolve to where the interesting part
is the polyrhythmic magic.

Polyrhythm can come raw, like Hatian drumming, or more sophisticate,
like Arsenio Rodrigues. (But notice that Rodrigues came out of Cuban
Congolese family of drummers before he took up the tres guitar.)

Even in purely drum music, things can also be rowdy or more
chill. E.g., Mali Drums, Old Masters:
https://michaelpluznick.com/music-shop/mali-drums-old-masters/

And just to be explicit, no sub-genre to to high or low as long as
the music is good:
https://www.youtube.com/watch?v=_P7S2lKif-A


** More
      
Another thing to note: I don't care about how old the music is. I
listen to Bach and Mozart essentially every day. 1920's Louis
Armstrong is on heavy rotation at my place. I am quite happy to listen
to the greatest music of days gone by.

Further, modern reinterpretations are also
of interest. One of my favorite renditions of Aquarela Do Brazil is
the 2006 acapella version by 4she:
https://www.youtube.com/watch?v=d5YbChg0XF0

Another reinterpretation example: Will.i.am's 2006 work with 
Sérgio Mendes:
https://www.youtube.com/playlist?list=OLAK5uy_m464HWinGSCNy2u7er--jCaRV3dUqIzi0

More modern music is of course on my radar but I don't put a lot of
energy into keeping current; mining history is easier because it's
already been sorted i.e. the greatest of old are already
identified. CeU is someone who broke through to the American
consciousness when Starbucks sold her first CD (yeah, CD :) in their
stores. I quite like her work:
https://www.youtube.com/channel/UC38xbd3KhfU8afjOQiix35A

I gotta say: I find some Brazilian music rather challenging to
appreciate. But that's true of all genres. As [[https://en.wikipedia.org/wiki/Sturgeon][Sturgeon said]]: "ninety
percent of everything is crap." But my ear is very open to challenges;
Some of Rite of Spring

Much like how AfroCubism is a mix of Afro-influenced artists from both
side of the Atlantic, another example of is the work of Batida (he's
Angolan/Portuguese and works with Brazilian musicians sometimes). Of
the music I reference in this document, Batida is the most futurist:
https://www.youtube.com/watch?app=desktop&v=w0yFmZIWaGM

I enjoy Batida's music but it does not inspire me to try to emulate
him. On the other hand, the other contemporary artist who I find
really exciting because of where his explorations take him is Daniel
M. A teacher of music, he has deep knowledge of Uruguay's candombe
rhythms in his muscle memory and he improvizes. For my own musical
creativity, this is very exciting: deeply incorporated polyrhythm into
one's mental memory seems to generated better improvization. Perhaps
it is because polyrhythm provides a musician in a song three
simultaneously maintained ways forward: rhythm one, rhythm two, and
the composite rhythm. At any time one of them can be productive, and
the other two are kept alive. So, I practice the rhythmic
fundamentals, which for me at this point in my development is
necessarily done at a very, very low tempo.


Historically American music is not polyrhythmic for two
reasons. Firstly, the whites simply did not allow the Africas to have
drums (they realized they were communicating in a Morse code style via
the drumming), The exceptions was Conga Square in New Orleans:
https://gonola.com/things-to-do-in-new-orleans/arts-culture/nola-history-congo-square-and-the-roots-of-new-orleans-music

Second, to put it very crudely, the slaves imported to American came
from the more northern part of the west side of Africa (shorter trip)
which is not the heart of polyrhythm, which is south of the
Sahara. The Arab influence north of the Sahara ensured that the music
of that region is melismatic i.e. more melodic and less
polyrhythmic. There are, of course exceptions, such as the gwana (the
reason being that is rooted in the music of slaves brought to Morocco
from south of the Sahara):
https://www.youtube.com/watch?v=V2eRThmqoYA

I'm also interested not just in enjoying the music but playing it and
comprehending it on a compositional level. Ergo, Rodrigeus.

What very little I know:
- Choro is poly?
- Samba is polyrhythmic?
- Axe, in that it exists

** Afro-Cuban
The most exciting Cuban album of this century that I've discovered is
Cachaito. This is a beautiful organic feeling blend of the old and
new, a continuation of the culture without a patina of nostalgia:
[[https://www.youtube.com/playlist?list=PLoDH1jJDcQERduDzCesH64qiokZWVfQxw][Cachaito Lopez (Buena Vista Social Club)]]

